### ISSUE TITLE
Question about the integration of Istio and Athenz

### ISSUE THREAD

**Issue by ryysud** [yahoo/k8s-athenz-istio-auth#45]
Hi, I have two questions about the integration of Istio and Athenz.

### Question1:

To maintainers,

The authorization policy model for access control in Istio 1.4, released on October 14 2019, has been replaced from the `v1alpha1 RBAC Policy` (Custom resources are ClusterRbacConfig, ServiceRole, ServiceRoleBinding) to `v1beta1 Authorization Policy` (Custom resource is AuthorizationPolicy).
https://istio.io/news/releases/1.4.x/announcing-1.4/#authorization-policy-model-in-beta

The `v1alpha1 RBAC Policy` used by `k8s-athenz-istio-auth` to integrate Athenz into Istio is now deprecated and will be removed in Istio 1.6.
https://archive.istio.io/v1.4/docs/reference/config/security/istio.rbac.v1alpha1/

Do you have a plan to support the new authorization policy model?

### Question2:

To `k8s-athenz-istio-auth` users,

What is the version of kubernetes and istio in the environment where `k8s-athenz-istio-auth` is installed?

**Comment by mcieplak** [comment]
Hi @ryysud 

Question 1: We are planning to start working on upgrading this controller to work for authorization policy towards the end of the third quarter (around September) before we upgrade istio to 1.6.

Question 2: We are currently running with istio 1.4.6 and kubernetes 1.15.9 in production.

**Comment by ryysud** [comment]
@mcieplak I understand. Thank you.
