### ISSUE TITLE
Support for K8s namespace level authorization in AuthorizationPolicy

### ISSUE THREAD

**Issue by mdhume** [yahoo/k8s-athenz-istio-auth#56]
**Please describe the problem that you are trying to solve**
[Istio Authorization policies](https://istio.io/latest/docs/reference/config/security/authorization-policy/) have support for authorizing all the services from a given namespace using an additional field [v1beta1.Rule_From.Source.Namespaces](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Source). If users provide an [Athenz role member](https://athenz.github.io/athenz/data_model/#roles) in the form of `<athenz-domain>.*` we should add the field `v1beta1.Rule_From.Source.Namespaces` to the corresponding AuthorizationPolicy to enable it.

**Describe the solution you'd like**

1. Update the [ConvertAthenzModelIntoIstioRbac](https://github.com/yahoo/k8s-athenz-istio-auth/blob/ed59085629060a3225391780e771a0fcfc4ecc47/pkg/istio/rbac/v2/provider.go#L34) to check the value of the role member. 
2. If the value of the role member:
    * contains a wildcard character `*` in the suffix
    * does not contain `user.` as the prefix
    then skip appending to `v1beta1.Rule_From.Source.Principals`
3. Convert the Athenz domain name into the corresponding Kubernetes namespace using the [DomainToNamespace](https://github.com/yahoo/k8s-athenz-istio-auth/blob/99afa06eb0882a35df486bb864066c313d47b366/pkg/athenz/util.go#L11) function
4. Create a `v1beta1.Rule_From.Source.Namespaces` array and append the generated namespace value to it

**Comment by patrasap0908** [comment]
Hi @mdhume, I'd like to take this one if that's okay.

**Comment by mcieplak** [comment]
PR has been merged, closing this issue. Thanks @patrasap0908 for your contribution!!
